services:
  mongo:
    image: mongo
    restart: always
    ports: # to access to mongo from host
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: usersdb
    networks: # to access to mongo from containers
      - shared

volumes:
  mongo_data:

networks:
  shared:
    external: true